version: "3.9"

services:
  app_client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_client
    entrypoint: "/bin/sh -c 'npm install && npm run dev'"
    init: true
    ports:
      - 15173:5173
    stdin_open: true
    tty: true
    volumes:
      - .:/root/app_client
    working_dir: /root/app_client
    user: root
